---
- hosts: localhost
  become: yes
  become_user: root
  vars:
    version: "{{ ansible_distribution_major_version }}"
  tasks:

    - name: Turn off SELinux
      selinux:
        state: disabled

    - name: Enabling RPMFusion repos
      tags: [repos, rpmfusion-repo]
      dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: yes
      with_items:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ version }}.noarch.rpm

    # - name: Enabling copr repos [Rust, gnome-twitch]
    #   tags: [repos, rust-repo]
    #   command: dnf copr enable -y {{ item }}
    #   args:
    #     creates: /etc/yum.repos.d/_copr_{{ item | replace("/", "-") }}.repo
    #   with_items:
    #     - fabiand/rust-binary
    #     - ippytraxx/gnome-twitch

    - name: Enabling custom repos [Spotify, Chrome, Skype]
      tags:
        - repos
        - spotify-repo
        - chrome-repo
        - skype-repo
      command: dnf config-manager --add-repo={{ item.url | default("repos") }}/{{ item.repo }}
      args:
        creates: /etc/yum.repos.d/{{ item.repo }}
      with_items:
        - url: http://negativo17.org/repos/
          repo: fedora-spotify.repo
        - repo: google-chrome.repo
        - repo: skype-stable.repo

    - name: Uninstall Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - shotwell
        - rhythmbox
          
    - name: Install Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - "@Development tools"
        - ShellCheck
        - cabal-install
        - cargo
        - clang-devel
        - cmake
        - corebird
        - ctags-etags
        - docbook-dtds
        - docbook-style-xsl
        - docker-compose
        - docker-io
        - emacs
        - epiphany
        - feedreader
        - flatpak
        - flatpak-builder
        - gimp
        - git
        - git-bz
        - gitflow
        - gitg
        - glade
        - gnome-calendar
        - gnome-common
        - gnome-maps
        - gnome-photos
        - gnome-tweak-tool
        - golang
        - golang-godoc
        - google-chrome-stable
        - gperf
        - gstreamer1-libav
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - gtk3-devel-docs
        - hunspell-sv
        - intltool
        - llvm-devel
        - llvm-static
        - lua-devel
        - lua-filesystem
        - luarocks
        - maven
        - meld
        - mercurial
        - meson
        - moreutils
        - nautilus-open-terminal
        - ncurses-devel
        - npm
        - p7zip-plugins
        - pandoc
        - perl-Errno
        - perl-open
        - pylint
        - python-autopep8
        - python-flake8
        - python-importmagic
        - python-ipython
        - python-jedi
        - python-pip
        - python-rope
        - remmina
        - remmina-plugins-gnome
        - remmina-plugins-rdp
        - remmina-plugins-vnc
        - rpmdevtools
        - rpmlint
        - ruby
        - ruby-irb
        - rust
        - skypeforlinux
        - spotify-client
        - systemd-container
        - the_silver_searcher
        - tig
        - tmux
        - transmission-remote-gtk
        - virt-manager
        - yelp-tools

    - name: Setup JHBuild Install dir
      file:
        path: /opt/gnome
        owner: root
        group: wheel
        mode: 0775
        state: directory
      tags: [jhbuild]
