---
- hosts: localhost
  become: true
  become_user: root
  vars_files:
    - packages.yaml
    - flatpaks.yaml
  vars:
    version: "{{ ansible_distribution_major_version }}"
  tasks:

    - name: Turn off coredumps
      sysctl:
        name: kernel.core_pattern
        state: present
        value: " "
        sysctl_file: /etc/sysctl.d/80-coredump.conf
      notify: Reload sysctl

    - name: Turn off SELinux
      selinux:
        state: disabled

    - name: Turn off services
      service:
        name: "{{ item }}.service"
        enabled: false
        state: stopped
      with_items:
        - ModemManager
        - abrtd
        - firewalld
        - gssproxy
        - livesys
        - sssd
        - switcheroo-control

    - name: Enable RPMFusion repos
      tags: [repos, rpmfusion-repo]
      dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items:
        - "http://download1.rpmfusion.org/free/fedora\
           /rpmfusion-free-release-{{ version }}.noarch.rpm"
        - "http://download1.rpmfusion.org/nonfree/fedora\
           /rpmfusion-nonfree-release-{{ version }}.noarch.rpm"

    - name: Enable custom repos [Chrome]
      tags:
        - repos
        - chrome-repo
        - skype-repo
      command: >
        dnf config-manager
          --add-repo={{ item.url | default("repos") }}/{{ item.repo }}
      args:
        creates: /etc/yum.repos.d/{{ item.repo }}
      with_items:
        - repo: google-chrome.repo

    - name: Uninstall Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - shotwell
        - rhythmbox

    - name: Install Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Add Flatpak remotes
      tags:
        - flatpak
        - repos
        - install
      command: "flatpak remote-add {{ item.remote }} {{ item.url }}"
      register: result
      failed_when:
        - "'already exists' not in result.stderr"
        - "result.rc != 0"
      changed_when:
        - "'already exists' not in result.stderr"
      with_items:
        - remote: gnome-nightly
          url: https://sdk.gnome.org/gnome-nightly.flatpakrepo
        - remote: gnome-apps-nightly
          url: https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo
        - remote: flathub
          url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak apps
      tags:
        - flatpak
        - apps
        - install
      command: "flatpak install -y {{ item.repo }} {{ item.name }}"
      register: result
      changed_when:
        - "'already installed, skipping' not in result.stderr"
      with_items: "{{ flatpaks }}"

    - name: Setup JHBuild Install dir
      file:
        path: /opt/gnome
        owner: root
        group: wheel
        mode: 0775
        state: directory
      tags: [jhbuild]

    - name: Setup sleep inhibitors [1/2]
      copy:
        src: "{{ item }}"
        dest: /usr/lib/systemd/system-sleep/
        owner: root
        group: wheel
        mode: 0755
      with_fileglob:
        - "./inhibitors/*.sh"

  handlers:
    - name: Reload sysctl
      command: /lib/systemd/systemd-sysctl
