---
- hosts: localhost
  become: true
  become_user: root
  vars:
    version: "{{ ansible_distribution_major_version }}"
  tasks:

    - name: Turn off coredumps
      sysctl:
        name: kernel.core_pattern
        state: present
        value: " "
        sysctl_file: /etc/sysctl.d/80-coredump.conf
      notify: Reload sysctl

    - name: Turn off SELinux
      selinux:
        state: disabled

    - name: Enable RPMFusion repos
      tags: [repos, rpmfusion-repo]
      dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items:
        - "http://download1.rpmfusion.org/free/fedora\
           /rpmfusion-free-release-{{ version }}.noarch.rpm"
        - "http://download1.rpmfusion.org/nonfree/fedora\
           /rpmfusion-nonfree-release-{{ version }}.noarch.rpm"

    - name: Enable custom repos [Chrome]
      tags:
        - repos
        - chrome-repo
        - skype-repo
      command: >
        dnf config-manager
          --add-repo={{ item.url | default("repos") }}/{{ item.repo }}
      args:
        creates: /etc/yum.repos.d/{{ item.repo }}
      with_items:
        - repo: google-chrome.repo

    - name: Uninstall Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - shotwell
        - rhythmbox

    - name: Install Packages
      tags: [packages]
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - "@Development tools"
        - ShellCheck
        - asciidoc
        - bison
        - cabal-install
        - cargo
        - clang-devel
        - cmake
        - corebird
        - ctags-etags
        - docbook-dtds
        - docbook-style-xsl
        - docker-compose
        - docker-io
        - nautilus-dropbox
        - emacs
        - epiphany
        - feedreader
        - flatpak
        - flatpak-builder
        - gimp
        - git
        - git-bz
        - gitflow
        - gitg
        - glade
        - gnome-books
        - gnome-calendar
        - gnome-common
        - gnome-maps
        - gnome-photos
        - gnome-tweak-tool
        - golang
        - golang-godoc
        - google-chrome-stable
        - gperf
        - groovy
        - gstreamer1-libav
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - gstreamer1-vaapi
        - gtk3-devel-docs
        - gtk-doc
        - flex
        - httpie
        - hunspell-sv
        - intltool
        - libva-intel-driver
        - llvm-devel
        - llvm-static
        - lastpass-cli
        - lua-devel
        - lua-filesystem
        - luarocks
        - maven
        - meld
        - mercurial
        - meson
        - moreutils
        - nautilus-open-terminal
        - ncurses-devel
        - npm
        - p7zip-plugins
        - pandoc
        - perl-Errno
        - perl-open
        - powerline
        - python-pip
        - python-devel
        - python3-devel
        - python2-pygpgme
        - ragel
        - remmina
        - remmina-plugins-gnome
        - remmina-plugins-rdp
        - remmina-plugins-vnc
        - rpmdevtools
        - rpmlint
        - rtags
        - ruby
        - ruby-irb
        - rust
        - sbt
        - systemd-container
        - the_silver_searcher
        - tig
        - tmux
        - transmission-remote-gtk
        - unrar
        - virt-manager
        - webkitgtk4-devel
        - yamllint
        - yelp-tools

    - name: Setup JHBuild Install dir
      file:
        path: /opt/gnome
        owner: root
        group: wheel
        mode: 0775
        state: directory
      tags: [jhbuild]

  handlers:
    - name: Reload sysctl
      command: /lib/systemd/systemd-sysctl
