---
# Workaround for: https://github.com/ansible/ansible/issues/14655
- hosts: localhost
  tasks:
    - command: echo

- hosts: localhost
  vars:
    version: "{{ ansible_distribution_major_version }}"
    install_prefix: "{{ ansible_user_dir }}/.local"
    config_prefix: "{{ ansible_user_dir }}/.config"
    code_dir: "{{ ansible_user_dir }}/Code"
    gnome_src: "{{ code_dir }}/gnome/src"
    gnome_build: "{{ code_dir }}/gnome/build"
    gh_mattiasb: git@github.com:mattiasb
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.local/bin/"

  tasks:
    - name: Fetch .local/bin
      tags:
        - fetch
        - update
        - localbin
      git:
        repo: "{{ gh_mattiasb }}/.local-bin.git"
        dest: "{{ ansible_user_dir }}/.local/bin"
        accept_hostkey: yes
        version: master

    # Needed if we haven't logged in to the desktop session yet, and
    # thus doesn't have a .config dir yet
    - name: Init Config Directory
      tags:
        - setup
        - config
      file:
        path: "{{ config_prefix }}"
        state: directory

    - name: Init Config Git Directory
      tags:
        - fetch
        - config
      command: git clone-here "{{ gh_mattiasb }}/.config.git"
      args:
        chdir: "{{ config_prefix }}"
        creates: "{{ config_prefix }}/.gitignore"

    - name: Fetch Config
      tags:
        - fetch
        - update
        - config
      git:
        repo: "{{ gh_mattiasb }}/.config.git"
        dest: "{{ config_prefix }}"
        version: master
      register: fetch_config

    - name: Link Configuration files
      tags:
        - setup
        - config
      file:
        src: "{{ config_prefix }}/{{ item.src | default(omit) }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: "{{ item.state }}"
      with_items:
        - dest: .bashrc
          state: absent
        - src: bash/rc
          dest: .bashrc
          state: link

        - dest: .bash_profile
          state: absent
        - src: bash/profile
          dest: .bash_profile
          state: link

        - dest: .bash_logout
          state: absent
        - src: bash/logout
          dest: .bash_logout
          state: link

        - dest: .rpmmacros
          state: absent
        - src: rpm/macros
          dest: .rpmmacros
          state: link

    - name: Update NPM Packages
      tags:
        - update
        - packages
        - npm
      command: npm install -g {{ item }}
      with_items:
        - eslint
        - grunt-cli
        - http-server
        - jake
        - jscs
        - jshint
        - yasel
      environment:
        NPM_CONFIG_USERCONFIG: "{{ config_prefix }}/npm/config"
      args:
        creates: "{{ install_prefix }}/bin/yasel"

    - name: Update LUA Packages
      tags:
        - update
        - packages
        - lua
      command: luarocks install {{ item }}
      environment:
        LUAROCKS_CONFIG: "{{ config_prefix }}/luarocks/config.lua"
      with_items:
        - luacheck
      args:
        creates: "{{ install_prefix }}/bin/luacheck"

    - name: Update go Packages
      tags:
        - update
        - packages
        - go
      command: go get -u {{ item }}
      with_items:
        - github.com/nsf/gocode
        - github.com/dougm/goflymake
        - github.com/rogpeppe/godef
      environment:
        GOBIN: "{{ install_prefix }}/bin"
        GOPATH: "{{ ansible_user_dir }}/Code/go:/usr/share/gocode"
      args:
        creates: "{{ install_prefix }}/bin/gocode"

    - name: Update Python Packages
      tags:
        - update
        - packages
        - python
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
      with_items:
        - git-spindle
        - scan-build

    - name: Update Rust Packages
      tags:
        - update
        - packages
        - rust
      command: cargo install {{ item }}
      with_items:
        - racer
        - rustfmt
      args:
        creates: "{{ install_prefix }}/bin/{{ item }}"
      environment:
        CARGO_HOME: "{{ install_prefix }}/share/cargo"
        CARGO_INSTALL_ROOT: "{{ install_prefix }}/"

    - name: Setup rpmdev
      tags:
        - setup
        - rpm
      command: rpmdev-setuptree
      args:
        creates: "{{ ansible_user_dir }}/Code/Fedora/rpmbuild/"

    - name: Setup JHBuild Directories
      tags:
        - setup
        - jhbuild
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gnome_build }}"
        - "{{ gnome_src }}"

    - include: fetch_install.yml
      vars:
        tag: jhbuild
        repo: "https://git.gnome.org/browse/jhbuild"
        dest: "{{ gnome_src }}/jhbuild"
        commands:
          - ./autogen.sh --prefix={{ install_prefix }}
          - make -j {{ ansible_processor_vcpus }}
          - make install

    - include: fetch_install.yml
      vars:
        tag: emacs
        repo: "{{ gh_mattiasb }}/.emacs.d.git"
        dest: "{{ ansible_user_dir }}/.emacs.d"
        commands:
          - make

    - include: fetch_install.yml
      vars:
        tag: git-fpaste
        repo: "{{ gh_mattiasb }}/git-fpaste.git"
        dest: "{{ code_dir }}/Projects/git-fpaste"
        creates: "{{ install_prefix }}/bin/git-fpaste"
        commands:
          - make user-install

    - include: fetch_install.yml
      vars:
        tag: git-each
        repo: git@github.com:tobias-johansson/git-each.git
        dest: "{{ code_dir }}/github/git-each"
        creates: "{{ install_prefix }}/bin/git-each"
        commands:
          - make user-install

    - include: fetch_install.yml
      vars:
        tag: git-wip
        repo: "{{ gh_mattiasb }}/git-wip.git"
        dest: "{{ code_dir }}/Projects/git-wip"
        creates: "{{ install_prefix }}/bin/git-wip"
        commands:
          - make user-install

    - include: fetch_install.yml
      vars:
        tag: rtags
        repo: git@github.com:Andersbakken/rtags.git
        dest: "{{ code_dir }}/github/rtags"
        build_dir: "{{ code_dir }}/github/rtags/build"
        creates: "{{ install_prefix }}/bin/rdm"
        commands:
          - cmake -DCMAKE_INSTALL_PREFIX:PATH="{{ install_prefix }}" ..
          - make -j {{ ansible_processor_vcpus }}
          - make install
          - systemctl --user enable rdm.socket
          - systemctl --user start rdm.socket

    - include: fetch_install.yml
      vars:
        tag: bear
        repo: git@github.com:rizsotto/Bear.git
        dest: "{{ code_dir }}/github/rizsotto/bear"
        build_dir: "{{ code_dir }}/github/rizsotto/bear/build"
        creates: "{{ install_prefix }}/bin/bear"
        commands:
          - cmake -DCMAKE_INSTALL_PREFIX:PATH="{{ install_prefix }}" ..
          - make -j {{ ansible_processor_vcpus }}
          - make install

    - name: GNOME settings
      tags:
        - gnome-settings
      command: gsettings set {{ item.schema }} {{ item.key }} "{{ item.value }}"
      with_items:
        - schema: org.baedert.corebird
          key: round-avatars
          value: "false"
        - schema: org.gnome.Terminal.Legacy.Settings
          key: theme-variant
          value: "'system'"
        - schema: org.gnome.desktop.interface
          key: gtk-key-theme
          value: "'Emacs'"
        - schema: org.gnome.desktop.peripherals.touchpad
          key: tap-to-click
          value: "true"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-1
          value: "['<Super>F1']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-2
          value: "['<Super>F2']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-3
          value: "['<Super>F3']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-4
          value: "['<Super>F4']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-5
          value: "['<Super>F5']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-6
          value: "['<Super>F6']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-7
          value: "['<Super>F7']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-8
          value: "['<Super>F8']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-9
          value: "['<Super>F9']"
        - schema: org.gnome.desktop.wm.keybindings
          key: panel-run-dialog
          value: "['<Super>r']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-1
          value: "['<Super>1']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-2
          value: "['<Super>2']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-3
          value: "['<Super>3']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-4
          value: "['<Super>4']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-5
          value: "['<Super>5']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-6
          value: "['<Super>6']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-7
          value: "['<Super>7']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-8
          value: "['<Super>8']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-9
          value: "['<Super>9']"
        - schema: org.gnome.desktop.wm.preferences
          key: action-middle-click-titlebar
          value: "'lower'"
        - schema: org.gnome.nautilus.preferences
          key: click-policy
          value: "'single'"
        - schema: org.gnome.settings-daemon.plugins.media-keys
          key: home
          value: "'<Super>f'"
        - schema: org.gnome.settings-daemon.plugins.media-keys
          key: www
          value: "'<Super>w'"
        - schema: org.gnome.shell
          key: favorite-apps
          value: "['firefox.desktop','evolution.desktop','spotify.desktop','org.baedert.corebird.desktop','org.gnome.Maps.desktop','org.gnome.Nautilus.desktop','org.gnome.Calendar.desktop','emacs.desktop','org.gnome.Software.desktop']"
        - schema: org.gnome.shell.app-switcher
          key: current-workspace-only
          value: "true"
        - schema: org.gnome.shell.calendar
          key: show-weekdate
          value: "true"
