---
- hosts: localhost
  vars:
    version: "{{ ansible_distribution_major_version }}"
    install_prefix: "{{ ansible_user_dir }}/.local"
    config_prefix: "{{ ansible_user_dir }}/.config"
    code_dir: "{{ ansible_user_dir }}/Code"
    gnome_src: "{{ code_dir }}/gnome/src"
    gnome_build: "{{ code_dir }}/gnome/build"
    gh_mattiasb: https://github.com/mattiasb

  tasks:
    - name: Fetch .local/bin
      tags:
        - fetch
        - update
        - localbin
      git:
        repo: "{{ gh_mattiasb }}/.local-bin.git"
        dest: "{{ ansible_user_dir }}/.local/bin"
        version: master

    - name: Init Config Git Directory
      tags:
        - fetch
        - config
      command: git clone-here "{{ gh_mattiasb }}/.config.git"
      args:
        chdir: "{{ config_prefix }}"
        creates: "{{ config_prefix }}/.gitignore"

    - name: Fetch Config
      tags:
        - fetch
        - update
        - config
      git:
        repo: "{{ gh_mattiasb }}/.config.git"
        dest: "{{ config_prefix }}"
        version: master
      register: fetch_config

    - name: Fetch Emacs Config
      tags:
        - fetch
        - emacs-config
      git:
        repo: "{{ gh_mattiasb }}/.emacs.d.git"
        dest: "{{ ansible_user_dir }}/.emacs.d"
        version: master
      register: fetch_emacs_config

    - name: Link Configuration files
      tags:
        - setup
        - config
      file:
        src: "{{ config_prefix }}/{{ item.src | default(omit) }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: "{{ item.state }}"
      with_items:
        - dest: .bashrc
          state: absent
        - src: bash/rc
          dest: .bashrc
          state: link

        - dest: .bash_profile
          state: absent
        - src: bash/profile
          dest: .bash_profile
          state: link

        - dest: .bash_logout
          state: absent
        - src: bash/logout
          dest: .bash_logout
          state: link

        - dest: .rpmmacros
          state: absent
        - src: rpm/macros
          dest: .rpmmacros
          state: link

    - name: Update NPM Packages
      tags:
        - update
        - packages
        - npm
      command: npm install -g {{ item }}
      with_items:
        - eslint
        - grunt-cli
        - http-server
        - jake
        - jscs
        - jshint
        - yasel
      environment:
        NPM_CONFIG_USERCONFIG: "{{ config_prefix }}/npm/config"

    - name: Update LUA Packages
      tags:
        - update
        - packages
        - lua
      command: luarocks install {{ item }}
      environment:
        LUAROCKS_CONFIG: "{{ config_prefix }}/luarocks/config.lua"
      with_items:
        - luacheck

    - name: Update go Packages
      tags:
        - update
        - packages
        - go
      command: go get {{ item }}
      with_items:
        - github.com/nsf/gocode
        - github.com/dougm/goflymake
        - github.com/rogpeppe/godef
        - github.com/monochromegane/the_platinum_searcher/...
      environment:
        GOBIN: "{{ install_prefix }}/bin"
        GOPATH: "{{ ansible_user_dir }}/Code/go:/usr/share/gocode"

    - name: Update Python Packages
      tags:
        - update
        - packages
        - python
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
      with_items:
        - git-spindle
        - scan-build

    - name: Update Rust Packages
      tags:
        - update
        - packages
        - rust
      command: cargo install {{ item }}
      with_items:
        - racer
        - rustfmt
      environment:
        CARGO_HOME: "{{ install_prefix }}/share/cargo"
        CARGO_INSTALL_ROOT: "{{ install_prefix }}/"
      args:
        creates:
          - "{{ install_prefix }}/bin/rustfmt"
          - "{{ install_prefix }}/bin/cargo"

    - name: Setup rpmdev
      tags:
        - setup
        - rpm
      command: rpmdev-setuptree
      args:
        creates: "{{ ansible_user_dir }}/Code/Fedora/rpmbuild/"

    - name: Setup JHBuild Directories
      tags:
        - setup
        - jhbuild
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gnome_build }}"
        - "{{ gnome_src }}"

    - name: Fetch JHBuild
      tags:
        - fetch
        - jhbuild
      git:
        repo: https://git.gnome.org/browse/jhbuild
        dest: "{{ gnome_src }}/jhbuild/"
        version: master
      register: fetch_jhbuild

    - name: Update JHBuild
      tags:
        - update
        - jhbuild
      command: "{{ item }}"
      with_items:
        - "./autogen.sh --prefix={{ install_prefix }}"
        - make
        - make install
      args:
        chdir: "{{ gnome_src }}/jhbuild/"
      when: fetch_jhbuild.changed

    - name: Update Emacs Config
      tags:
        - update
        - emacs-config
      command: make update
      args:
        chdir: "{{ ansible_user_dir }}/.emacs.d"
      when: fetch_emacs_config.changed

    - name: Fetch git-fpaste
      tags:
        - fetch
        - git-fpaste
      git:
        repo: "{{ gh_mattiasb }}/git-fpaste.git"
        dest: "{{ code_dir }}/Projects/git-fpaste"
        version: master
        update: yes
      register: fetch_git_fpaste

    - name: Install git-fpaste
      tags:
        - install
        - git-fpaste
      command: make user-install
      args:
        chdir: "{{ code_dir }}/Projects/git-fpaste"
      when: fetch_git_fpaste.changed

    ## TODO:
    #  - Install RTags
