---
# Set up facts
- hosts: localhost
  tasks:
    - command: "flatpak remote-list --user"
      register: flatpak_remotes
    - set_fact:
        flatpak_remotes: >
          {{ flatpak_remotes.stdout_lines
            | regex_replace(' *','') }}

    - command: "flatpak list --user --show-details"
      register: flatpak_apps
    - set_fact:
        flatpak_apps: >
          {{ flatpak_apps.stdout_lines
           | map('regex_replace', '^(\S+).*$','\1')
           | list }}

    - command: "rustc --version"
      register: rustc_version
    - set_fact:
        rustc_version: "{{ rustc_version.stdout.split(' ')[1] }}"

    - command: pandoc --bash-completion
      register: pandoc_bash_completion
    - command: npm completion
      register: npm_bash_completion
    - set_fact:
        bash_completion:
          - name: npm
            content: "{{ npm_bash_completion.stdout }}"
          - name: pandoc
            content: "{{ pandoc_bash_completion.stdout }}"

- hosts: localhost
  vars:
    version: "{{ ansible_distribution_major_version }}"
    install_prefix: "{{ ansible_user_dir }}/.local"
    config_prefix: "{{ ansible_user_dir }}/.config"
    code_dir: "{{ ansible_user_dir }}/Code"
    gnome_src: "{{ code_dir }}/gnome/src"
    gnome_build: "{{ code_dir }}/gnome/build"
    gh_mattiasb: git@github.com:mattiasb
    gl_mattiasb: git@gitlab.com:mattiasb
    pip_modules:
      - autopep8
      - epc
      - flake8
      - git-spindle
      - ipdb
      - ipython
      - isort
      - jedi
      - importmagic
      - rope
      - scan-build
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.local/bin/"

  tasks:
    - name: Fetch .local/bin
      tags:
        - fetch
        - update
        - localbin
      git:
        repo: "{{ gh_mattiasb }}/.local-bin.git"
        dest: "{{ ansible_user_dir }}/.local/bin"
        accept_hostkey: true
        version: master

    # Needed if we haven't logged in to the desktop session yet, and
    # thus doesn't have a .config dir yet
    - name: Init Config Directory
      tags:
        - setup
        - config
      file:
        path: "{{ config_prefix }}"
        state: directory

    - name: Init Config Git Directory
      tags:
        - fetch
        - config
      command: git clone-here "{{ gh_mattiasb }}/.config.git"
      args:
        chdir: "{{ config_prefix }}"
        creates: "{{ config_prefix }}/.gitignore"

    - name: Fetch Config
      tags:
        - fetch
        - update
        - config
      git:
        repo: "{{ gh_mattiasb }}/.config.git"
        dest: "{{ config_prefix }}"
        version: master
      register: fetch_config

    - name: Link Configuration files
      tags:
        - setup
        - config
      file:
        src: "{{ config_prefix }}/{{ item.src | default(omit) }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: "{{ item.state }}"
      with_items:
        - dest: .bashrc
          state: absent
        - src: bash/rc
          dest: .bashrc
          state: link

        - dest: .bash_profile
          state: absent
        - src: bash/profile
          dest: .bash_profile
          state: link

        - dest: .bash_logout
          state: absent
        - src: bash/logout
          dest: .bash_logout
          state: link

        - dest: .rpmmacros
          state: absent
        - src: rpm/macros
          dest: .rpmmacros
          state: link

        - dest: .inputrc
          state: absent
        - src: inputrc
          dest: .inputrc
          state: link

    - name: Enable systemd user units
      systemd:
        name: rdm.socket
        user: true
        enabled: true
        daemon_reload: true
        state: started

    - name: Generate bash completion files
      tags:
        - update
        - bash
        - completion
      copy:
        content: "{{ item.content }}"
        dest: "{{ config_prefix }}/bash_completion.d/{{ item.name }}"
      with_items: "{{ bash_completion }}"

    - name: Fetch mtg-decks
      tags:
        - fetch
        - update
        - mtg-decks
      git:
        repo: "{{ gl_mattiasb }}/mtg-decks.git"
        dest: "{{ ansible_user_dir }}/Documents/Magic/decks"
        accept_hostkey: true
        version: master

    - name: Add Flatpak remotes
      tags:
        - flatpak
        - repos
        - install
      command: >
        flatpak --user remote-add
                --from {{ item.remote }}
                {{ item.url }}
      with_items:
        - remote: gnome
          url: https://sdk.gnome.org/gnome.flatpakrepo
        - remote: gnome-apps
          url: https://sdk.gnome.org/gnome-apps.flatpakrepo
        - remote: gnome-nightly
          url: https://sdk.gnome.org/gnome-nightly.flatpakrepo
        - remote: gnome-apps-nightly
          url: https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo
      when: item.remote not in flatpak_remotes

    - name: Install Flatpak apps
      tags:
        - flatpak
        - apps
        - install
      command: "flatpak install -y --user {{ item.repo }} {{ item.name }}"
      with_items:
        - name: org.gnome.Builder/x86_64/master
          repo: gnome-apps-nightly
        - name: org.gnome.Builder/x86_64/stable
          repo: gnome-apps
        - name: org.gnome.Games/x86_64/stable
          repo: gnome-apps
        - name: org.gnome.Games/x86_64/master
          repo: gnome-apps-nightly
        - name: org.gnome.Maps/x86_64/stable
          repo: gnome-apps
        - name: org.gnome.Maps/x86_64/master
          repo: gnome-apps-nightly
        - name: org.gnome.Epiphany/x86_64/master
          repo: gnome-apps-nightly
      when: item.name not in flatpak_apps

    - name: Install Flatpak apps (via refs)
      tags:
        - flatpak
        - apps
        - install
      command: "flatpak install -y --user --from {{ item.url }}"
      with_items:
        - url: https://dl.tingping.se/flatpak/gnome-twitch.flatpakref
          name: com.vinszent.GnomeTwitch/x86_64/master
        - url: https://flatpak.perezdecastro.org/revolt.flatpakref
          name: org.perezdecastro.Revolt/x86_64/master
        - url: "https://s3.amazonaws.com/alexlarsson\
                /spotify-repo/spotify.flatpakref"
          name: com.spotify.Client/x86_64/master
      when: item.name not in flatpak_apps

    - name: Update NPM Packages
      tags:
        - update
        - packages
        - npm
      command: npm install -g {{ item }}
      with_items:
        - eslint
        - grunt-cli
        - http-server
        - jake
        - jscs
        - jshint
        - yasel
      environment:
        NPM_CONFIG_USERCONFIG: "{{ config_prefix }}/npm/config"
      args:
        creates: "{{ install_prefix }}/bin/yasel"

    - name: Update LUA Packages
      tags:
        - update
        - packages
        - lua
      command: luarocks install {{ item }}
      environment:
        LUAROCKS_CONFIG: "{{ config_prefix }}/luarocks/config.lua"
      with_items:
        - luacheck
      args:
        creates: "{{ install_prefix }}/bin/luacheck"

    - name: Update go Packages
      tags:
        - update
        - packages
        - go
      command: go get -u {{ item }}
      with_items:
        - github.com/nsf/gocode
        - github.com/dougm/goflymake
        - github.com/rogpeppe/godef
      environment:
        GOBIN: "{{ install_prefix }}/bin"
        GOPATH: "{{ ansible_user_dir }}/Code/go:/usr/share/gocode"
      args:
        creates: "{{ install_prefix }}/bin/gocode"

    - name: Update Python 2 Packages
      tags:
        - update
        - packages
        - python2
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
        executable: pip2
      with_items: "{{ pip_modules }}"

    - name: Update Python 3 Packages
      tags:
        - update
        - packages
        - python3
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
        executable: pip3
      with_items: "{{ pip_modules }}"

    - name: Get Rust source
      tags:
        - fetch
        - rust-src
      git:
        repo: git@github.com:rust-lang/rust.git
        dest: "{{ code_dir }}/github/rust-lang/rust"
        accept_hostkey: true
        version: "{{ rustc_version }}"

    - name: Update Rust Packages
      tags:
        - update
        - packages
        - rust
      command: cargo install {{ item.pkg }}
      with_items:
        - pkg: racer
        - pkg: rustfmt
        - pkg: ripgrep
          bin: rg
      args:
        creates: "{{ install_prefix }}/bin/{{ item.bin | default(item.pkg) }}"
      environment:
        CARGO_HOME: "{{ install_prefix }}/share/cargo"
        CARGO_INSTALL_ROOT: "{{ install_prefix }}/"

    - name: Setup rpmdev
      tags:
        - setup
        - rpm
      command: rpmdev-setuptree
      args:
        creates: "{{ ansible_user_dir }}/Code/Fedora/rpmbuild/"

    - name: Setup JHBuild Directories
      tags:
        - setup
        - jhbuild
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gnome_build }}"
        - "{{ gnome_src }}"

    - include: fetch_install.yaml
      static: false
      vars:
        tag: fonts
        repo: git@github.com:domtronn/all-the-icons.el.git
        dest: "{{ code_dir }}/github/domtronn/all-the-icons.el"
        install:
          src: fonts/*.ttf
          dest: "{{ install_prefix }}/share/fonts/"
          mode: "0644"

    - include: fetch_install.yaml
      static: false
      vars:
        tag: jhbuild
        repo: "https://git.gnome.org/browse/jhbuild"
        dest: "{{ gnome_src }}/jhbuild"
        commands:
          - ./autogen.sh --prefix={{ install_prefix }}
          - make -j {{ ansible_processor_vcpus }}
          - make install

    - include: fetch_install.yaml
      static: false
      vars:
        tag: emacs
        repo: "{{ gh_mattiasb }}/.emacs.d.git"
        dest: "{{ ansible_user_dir }}/.emacs.d"
        commands:
          - make

    - include: fetch_install.yaml
      static: false
      vars:
        tag: git-fpaste
        repo: "{{ gh_mattiasb }}/git-fpaste.git"
        dest: "{{ code_dir }}/Projects/git-fpaste"
        creates: "{{ install_prefix }}/bin/git-fpaste"
        commands:
          - make user-install

    - include: fetch_install.yaml
      static: false
      vars:
        tag: git-each
        repo: git@github.com:tobias-johansson/git-each.git
        dest: "{{ code_dir }}/github/git-each"
        creates: "{{ install_prefix }}/bin/git-each"
        commands:
          - make user-install

    - include: fetch_install.yaml
      static: false
      vars:
        tag: git-wip
        repo: "{{ gh_mattiasb }}/git-wip.git"
        dest: "{{ code_dir }}/Projects/git-wip"
        creates: "{{ install_prefix }}/bin/git-wip"
        commands:
          - make user-install

    - include: fetch_install.yaml
      static: false
      vars:
        tag: bear
        repo: git@github.com:rizsotto/Bear.git
        dest: "{{ code_dir }}/github/rizsotto/bear"
        build_dir: "{{ code_dir }}/github/rizsotto/bear/build"
        creates: "{{ install_prefix }}/bin/bear"
        commands:
          - cmake -DCMAKE_INSTALL_PREFIX:PATH="{{ install_prefix }}" ..
          - make -j {{ ansible_processor_vcpus }}
          - make install

    - name: GNOME settings
      tags:
        - gnome-settings
      command: gsettings set {{ item.schema }} {{ item.key }} "{{ item.value }}"
      with_items:
        - schema: org.baedert.corebird
          key: round-avatars
          value: "false"
        - schema: org.gnome.Terminal.Legacy.Settings
          key: theme-variant
          value: "'system'"
        - schema: org.gnome.desktop.interface
          key: gtk-key-theme
          value: "'Emacs'"
        - schema: org.gnome.desktop.peripherals.touchpad
          key: tap-to-click
          value: "true"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-1
          value: "['<Super>F1']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-2
          value: "['<Super>F2']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-3
          value: "['<Super>F3']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-4
          value: "['<Super>F4']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-5
          value: "['<Super>F5']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-6
          value: "['<Super>F6']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-7
          value: "['<Super>F7']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-8
          value: "['<Super>F8']"
        - schema: org.gnome.desktop.wm.keybindings
          key: move-to-workspace-9
          value: "['<Super>F9']"
        - schema: org.gnome.desktop.wm.keybindings
          key: panel-run-dialog
          value: "['<Super>r']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-1
          value: "['<Super>1']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-2
          value: "['<Super>2']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-3
          value: "['<Super>3']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-4
          value: "['<Super>4']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-5
          value: "['<Super>5']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-6
          value: "['<Super>6']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-7
          value: "['<Super>7']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-8
          value: "['<Super>8']"
        - schema: org.gnome.desktop.wm.keybindings
          key: switch-to-workspace-9
          value: "['<Super>9']"
        - schema: org.gnome.desktop.wm.preferences
          key: action-middle-click-titlebar
          value: "'lower'"
        - schema: org.gnome.nautilus.preferences
          key: click-policy
          value: "'single'"
        - schema: org.gnome.settings-daemon.plugins.media-keys
          key: home
          value: "'<Super>f'"
        - schema: org.gnome.settings-daemon.plugins.media-keys
          key: www
          value: "'<Super>w'"
        - schema: org.gnome.shell.app-switcher
          key: current-workspace-only
          value: "true"
