---
gsettings:
  - key: "/org/gnome/Terminal/Legacy/Settings/theme-variant"
    value: "'system'"
  - key: "/org/gnome/Terminal/Legacy/Settings/default-show-menubar"
    value: "false"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
  - key: "/org/gnome/system/locale/region"
    value: "'sv_SE.UTF-8'"
  - key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"
  - key: "/org/gnome/desktop/interface/gtk-key-theme"
    value: "'Emacs'"
  - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
  - key: "/org/gnome/desktop/search-providers/disable-external"
    value: "true"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1"
    value: "['<Super>F1']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2"
    value: "['<Super>F2']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3"
    value: "['<Super>F3']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4"
    value: "['<Super>F4']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5"
    value: "['<Super>F5']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6"
    value: "['<Super>F6']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-7"
    value: "['<Super>F7']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-8"
    value: "['<Super>F8']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-9"
    value: "['<Super>F9']"
  - key: "/org/gnome/desktop/wm/keybindings/panel-run-dialog"
    value: "['<Super>r']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
    value: "['<Super>1']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
    value: "['<Super>2']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
    value: "['<Super>3']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
    value: "['<Super>4']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5"
    value: "['<Super>5']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6"
    value: "['<Super>6']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7"
    value: "['<Super>7']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8"
    value: "['<Super>8']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9"
    value: "['<Super>9']"
  - key: "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar"
    value: "'lower'"
  - key: "/org/gnome/nautilus/preferences/click-policy"
    value: "'single'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "'<Super>f'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "'<Super>w'"
  - key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
